-- Книга собственников (ст. 7 ЗУЕС): тип обитателя и животные с чипом/паспортом.
-- Выполните в SQL Editor проекта Supabase.

alter table public.properties
  add column if not exists occupant_kind text not null default 'owner';

alter table public.properties
  add column if not exists occupant_name text;

alter table public.properties
  add column if not exists occupant_phone text;

alter table public.properties
  add column if not exists occupant_email text;

alter table public.properties
  add column if not exists occupant_until date;

alter table public.apartment_guests
  add column if not exists is_permanent boolean not null default true;

create table if not exists public.apartment_pets (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  property_id integer not null references public.properties (id) on delete cascade,
  species text not null default 'dog',
  name text,
  chip_no text,
  passport_no text,
  notes text
);

create index if not exists apartment_pets_property_id_idx
  on public.apartment_pets (property_id);

alter table public.apartment_pets enable row level security;

drop policy if exists "apartment_pets_all" on public.apartment_pets;
create policy "apartment_pets_all" on public.apartment_pets
  for all using (true) with check (true);

grant select, insert, update, delete on table public.apartment_pets to anon, authenticated;
